# Generated by Django 5.2.2 on 2025-10-23 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('students', models.IntegerField(verbose_name='Talabalar soni')),
                ('exp', models.IntegerField(verbose_name='Tajriba yili')),
                ('teachers', models.IntegerField(verbose_name='O‘qituvchilar soni')),
                ('graduates', models.IntegerField(verbose_name='Bitiruvchilar soni')),
                ('image', models.ImageField(upload_to='about_photos/', verbose_name='Rasm')),
                ('lat', models.CharField(max_length=255, verbose_name='Latitude')),
                ('lot', models.CharField(max_length=255, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': 'Biz haqimizda (tartiblar)',
                'db_table': 'about',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavha')),
                ('description', models.CharField(max_length=200, verbose_name='Izoh')),
                ('image', models.ImageField(upload_to='banner_photos/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
                'db_table': 'banner',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(max_length=100, verbose_name='Filial nomi')),
                ('about', models.TextField(verbose_name='Tavsif')),
                ('image', models.ImageField(upload_to='branch_photos/', verbose_name='Rasm')),
                ('lat', models.CharField(max_length=255, verbose_name='Latitude')),
                ('lot', models.CharField(max_length=255, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'db_table': 'branch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
                'db_table': 'contact_us',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('image', models.ImageField(upload_to='course_photos/', verbose_name='Rasm')),
                ('name', models.CharField(max_length=50, verbose_name='Kurs nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('duration', models.IntegerField(verbose_name='Davomiyligi (oy)')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'db_table': 'course',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('students', models.IntegerField(verbose_name='Talabalar soni')),
                ('year_exp', models.IntegerField(verbose_name='Tajriba yili')),
                ('employment', models.IntegerField(verbose_name='Ishga joylashish foizi')),
                ('university_student', models.IntegerField(verbose_name='Universitet talabasi')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
                'db_table': 'home_stats',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('youtube', models.URLField(verbose_name='YouTube')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('location', models.CharField(max_length=100, verbose_name='Manzil')),
            ],
            options={
                'verbose_name': 'Ijtimoiy tarmoq',
                'verbose_name_plural': 'Ijtimoiy tarmoqlar',
                'db_table': 'social_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(max_length=50, verbose_name='Fan nomi')),
                ('image', models.ImageField(upload_to='Subject_photos', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Fan',
                'verbose_name_plural': 'Fanlar',
                'db_table': 'subject',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('image', models.ImageField(upload_to='teacher_photos/', verbose_name='Rasm')),
                ('full_name', models.CharField(max_length=100, verbose_name='F.I.Sh')),
                ('subject', models.CharField(max_length=50, verbose_name='Fan')),
                ('about', models.TextField(verbose_name='O‘qituvchi haqida')),
                ('instagram', models.URLField(verbose_name='Instagram')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('facebook', models.URLField(verbose_name='Facebook')),
                ('video', models.URLField(verbose_name='Video havola')),
            ],
            options={
                'verbose_name': 'O‘qituvchi',
                'verbose_name_plural': 'O‘qituvchilar',
                'db_table': 'teacher',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(max_length=50, verbose_name='Nomi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='main.course')),
            ],
            options={
                'verbose_name': 'Yo‘l xaritasi',
                'verbose_name_plural': 'Yo‘l xaritalari',
                'db_table': 'course_roadmap',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseRoadMapField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('info', models.TextField(verbose_name='Tavsif')),
                ('road_maop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_road_map', to='main.courseroadmap')),
            ],
            options={
                'verbose_name': 'Yo‘l xaritasi matni',
                'verbose_name_plural': 'Yo‘l xaritasi matnlari',
                'db_table': 'course_roadmap_field',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('name', models.CharField(max_length=100, verbose_name='Savol')),
                ('answer1', models.CharField(max_length=50, verbose_name='Variant 1')),
                ('answer2', models.CharField(max_length=50, verbose_name='Variant 2')),
                ('answer3', models.CharField(max_length=50, verbose_name='Variant 3')),
                ('answer4', models.CharField(max_length=50, verbose_name='Variant 4')),
                ('correct_answer', models.IntegerField(choices=[(1, 'Variant 1'), (2, 'Variant 2'), (3, 'Variant 3'), (4, 'Variant 4')], verbose_name='To‘g‘ri javob')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'db_table': 'quiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('image', models.ImageField(upload_to='Certificate_photos/', verbose_name='Rasm')),
                ('full_name', models.CharField(max_length=100, verbose_name='F.I.Sh')),
                ('level', models.CharField(max_length=100, verbose_name='Daraja')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name='Fan')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'db_table': 'certificate',
                'ordering': ['-created_at'],
            },
        ),
    ]
