# Generated by Django 5.2.7 on 2025-10-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "Oson"), ("medium", "O‘rta"), ("hard", "Qiyin")],
                default="medium",
                max_length=10,
                verbose_name="Qiyinchilik darajasi",
            ),
        ),
    ]
